# Generated by Django 5.2.8 on 2025-12-03 09:06

from django.db import migrations
from django.contrib.auth import get_user_model

def create_admin_user(apps, schema_editor):
    """Crear usuario administrador por defecto"""
    User = get_user_model()
    
    # Verificar si el usuario admin ya existe
    if not User.objects.filter(username='admin').exists():
        admin_user = User.objects.create_user(
            username='admin',
            email='admin@example.com',
            password='Fuengirola1.',
            first_name='Administrateur',
            last_name='Système'
        )
        admin_user.is_staff = True
        admin_user.is_superuser = True
        admin_user.save()

def reverse_create_admin_user(apps, schema_editor):
    """Eliminar usuario administrador (para rollback)"""
    User = get_user_model()
    User.objects.filter(username='admin').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_admin_user, reverse_create_admin_user),
    ]
