# Generated by Django 5.2.8 on 2025-12-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20251203_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='visitor_id',
            field=models.CharField(blank=True, help_text='UUID único por visitante', max_length=36),
        ),
    ]
